name: client
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cloud_firestore: ^3.1.5
  firebase_auth: ^3.3.4
  firebase_core: ^1.10.6
  firebase_storage: ^10.2.4
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_svg: ^1.0.0
  get: ^4.6.1
  image_picker: ^0.8.4+4
  intl_phone_number_input: ^0.7.0+2
  shared_preferences: ^2.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_native_splash: ^1.3.2
  flutter_launcher_icons: ^0.9.2

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/

flutter_native_splash:
  color: "#F27121"
  image: assets/images/3.0x/flutter_logo.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/sports.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "dev_assets/sports.png"
